import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated from files under `docs/`.
 * Add any `.md` / `.mdx` file there and it appears in the sidebar.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
